# Generated by Django 4.1 on 2024-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=10, unique=True)),
                ("workerId", models.IntegerField()),
                ("password", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
