# Generated by Django 4.1 on 2024-05-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appusers",
            name="password",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
