# Generated by Django 4.1 on 2024-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_alter_appusers_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentName", models.CharField(max_length=30)),
                ("studentId", models.CharField(max_length=6, unique=True)),
                ("paymentDate", models.DateField()),
                ("level", models.CharField(max_length=5)),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="AppUsers",
        ),
    ]
